### PR TITLE
update gsbug.h prototypes and errors based on gsbug and niftylist

### PR DESCRIPTION
**Pull request by ksherlock**

### CODE REVIEW

**Comment by sheumann** [comment]
The part of this that adds prototypes for the existing GSBug calls generally looks good, although I think the parameter type for `DebugSetHook` could maybe be `VoidProcPtr`. (It's a pointer to code that can be called, and AFAIK the hook procedure could probably be written in ORCA/C, although I haven't tried it.)

With regard to the added calls and constants, are these actually implemented and/or documented in a version of GSBug that was officially released by Apple? If not, I'm not sure they should be included in the header.

**Comment by ksherlock** [comment]
Good question.  `DebugQuery`, `DebugControl` and `dgiOAEscEntry` look like they were added in May 1993 as part of GSBug 1.7 development.  I can't find  any released version newer than 1.6.  May 1993 looks like it was the last Apple developer CD with Apple II content and that had GSBug 1.6.

**Comment by sheumann** [comment]
Thank you for checking on the versions. It looks like GSBug 1.6 probably only uses the `debugUnImpErr` and `debugBadSelErr` error codes, so can you also remove the other error codes for consistency?

**Comment by ksherlock** [comment]
They have been removed.

**Comment by MikeW50** [comment]
I'm relying on 30 year old memories, but GSBug was not the only debugger, and I think they may have overlapped on error code usage. Did you check the debugger in Prism to make sure it was not using these error codes? There was at least one more debugger, but I guess it doesn't matter much if it is not on the disk and none of us can remember it. :)

**Pull request merged**
